- hosts: localhost
  gather_facts: no

  tasks:

    - name: Load secrets
      include_vars:
        file: vcsa_secrets.yaml
        name: vcsa_secrets
    - name: Debug
      debug:
        msg: "{{ vcsa_secrets }}"
    - name: Gather info 
      vmware_about_info:
        hostname: "{{ vcsa_secrets.hostname }}"
        username: "{{ vcsa_secrets.username }}"
        password: "{{ vcsa_secrets.password }}"
        validate_certs: no
      delegate_to: localhost
      register: vmware_info
    - name: Debug info
      debug:
        msg: "{{ vmware_info }}"
    - name: Gather info about all customization specification
      vmware_guest_customization_info:
        hostname: "{{ vcsa_secrets.hostname }}"
        username: "{{ vcsa_secrets.username }}"
        password: "{{ vcsa_secrets.password }}"
        spec_name: RedHat
        validate_certs: no
      delegate_to: localhost
      register: all_custom_spec_info
